### ISSUE TITLE
A version for scalapb 0.7.0 rc6

### ISSUE THREAD

**Issue by ngbinh** [scalapb-json/scalapb-json-common#1]
It contains some breaking changes https://github.com/scalapb/ScalaPB/releases/tag/v0.7.0-rc6

**Comment by xuwei-k** [comment]
I'll release new version in a few days.

**Comment by xuwei-k** [comment]
scalapb-json-common 0.2.0-M1 released with scalapb 0.7.0-rc7
- https://github.com/scalapb-json/scalapb-json-common/commit/a9cb0157f5186ce2c926cca3f9226dfbf3121903
- https://github.com/scalapb-json/scalapb-json-common/compare/v0.1.1...v0.2.0-M1

**Comment by ngbinh** [comment]
thanks
